Implementation/ABET_Document_Manager/config/routes.rb
Rails.application.routes.draw do

  
  get 'offerings/index'
  get 'offerings/view', to: 'offerings#view'
	

  get 'documents/docview', to: 'documents#docview'
  get 'documents/all', to: 'documents#all'
  
  patch 'documents/update', to: 'documents#update'
  put 'documents/update', to: 'documents#update'
	patch 'documents/update_status', to: 'documents#update_status'
	put 'documents/update_status', to: 'documents#update_status'

  get '/documents/:id', to: 'documents#docview'

  root 'sessions#new'
  get 'browse/index', to: 'documents#index'
  get 'master_matrices/index'
  get 'master_matrices/delete'

	resources :abet_metrics, only: [:create, :destroy]
  resources :documents, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :course_track_lists
  resources :libraries
  resources :approvers
  resources :master_matrices
  resources :sys_admin, only: [:index]
  resources :abet_outcomes
  resources :documents
  resources :degrees
  resources :tracks
  resources :courses
  resources :users
  resources :teachings
  resources :offerings, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :pies
  resources :airs
  resources :eocms
	
	put 'offerings/evaluation/:id', to: 'offerings#evaluation'
	put 'abet_metrics/evaluation/:id', to: 'abet_metrics#evaluation'

  get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

end

Implementation/ABET_Document_Manager/app/models/course_track_list.rb
class CourseTrackList < ActiveRecord::Base
  belongs_to :track
  belongs_to :course
end

Implementation/ABET_Document_Manager/app/controllers/course_track_lists_controller.rb
class CourseTrackListsController < ApplicationController
  def index
  	@course_track_lists = CourseTrackList.joins(:course, :track)
  end

  def show
  	@course_track_list = CourseTrackList.joins(:course, :track).find params[:id]
  end

  def edit
  	@course_track_list = CourseTrackList.find params[:id]
  end

  def update
  	course_track_list = CourseTrackList.find params[:id]
  	if course_track_list.update_attributes(course_track_list_params)
  		redirect_to sys_admin_index_path, :notice => 'The course_track_list has successfully been updated.'
  	else
  		redirect_to :back, :notice => 'There was an error updating the course_track_list.'
  	end
  end

  def create
  	CourseTrackList.create(course_track_list_params)
  	redirect_to :back, :notice => 'The course_track_list has successfully been created.'
  end

  def destroy
  	CourseTrackList.destroy params[:id]
  	redirect_to :back, :notice => "The course_track_list has been removed."
  end

  private
  def course_track_list_params
  	params.require(:course_track_list).permit(:course_id, :track_id)
  end
end

Implementation/ABET_Document_Manager/app/helpers/course_track_lists_helper.rb
module CourseTrackListsHelper
end

Implementation/ABET_Document_Manager/app/views/course_track_lists/edit.html.erb
<center>
<h1><span class="label label-primary">Editing Course Track List</span></h1>
</center>

  <%= form_for @course_track_list, class: 'form-inline'   do |f| %>
  <%= f.label :track_id  %>
  <!-- <%= f.text_field :track_id,  {class: "form-control" , style:  "width:350px"} %> -->
  <%= f.collection_select :track_id, Track.all.order('name ASC'), :id, :name, :prompt => "Select" %>
  <%= f.label :course_id %>
  <!-- <%= f.text_field :course_id , {class: "form-control" , style:  "width:350px"} %> -->
  <%= f.collection_select :course_id, Course.all.order('name ASC'), :id, :name, :prompt => "Select" %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %>  
  <center>
  <%= link_to "<button type='button' class='btn btn-danger'> Cancel </button>".html_safe , sys_admin_index_path%>
  </center>

Implementation/ABET_Document_Manager/app/views/course_track_lists/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <h2><span class="label label-primary">Course Track List Index</span></h2>
  
 <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#courseTrackAdd">Add Course to Track</button>

 <div id="courseTrackAdd" class="collapse">

  <%= form_for CourseTrackList.new, class: 'form-inline'   do |f| %>
  <%= f.label :track_id  %>
  <%= f.text_field :track_id,  {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :course_id %>
  <%= f.text_field :course_id , {class: "form-control" , style:  "width:350px"} %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %>
 </div> 
  <!-- Table for degrees -->
  <table class="table"  >
   
    <thead>
      <tr>
        <th><%= "Track: "%></th>
        <th><%= "Course: "%></th>
      </tr>
    </thead>
    
    <tbody>
    <% @course_track_lists.each do |ctl| %>
      <tr>
          <td><%= ctl.track.name %></td>
          <td><%= ctl.course.name %></td>
        <td> <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>  <%= link_to 'Details', course_track_lists_path(ctl) %></td>
      </tr>
   <% end %>
  
    </tbody>
    
  </table>
  
  <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>

  
</div>

Implementation/ABET_Document_Manager/app/views/course_track_lists/show.html.erb
<% ctl = @course_track_list %>
 <center>
<h1><span class="label label-primary">Showing Course Track List:</span></h1>
<h3><span class="label label-info"><%= ":"%></span> <%= ctl.track.name %></h3>
<h3><span class="label label-info"><%= ":"%></span> <%= ctl.course.name %></h3>
 
 

  <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>
  <%= link_to "<button type='button' class='btn btn-default'> Edit </button>".html_safe , edit_course_track_list_path(ctl) %>
 </center>