Implementation/ABET_Document_Manager/config/routes.rb
Rails.application.routes.draw do

  
  get 'offerings/index'
  get 'offerings/view', to: 'offerings#view'
	

  get 'documents/docview', to: 'documents#docview'
  get 'documents/all', to: 'documents#all'
  
  patch 'documents/update', to: 'documents#update'
  put 'documents/update', to: 'documents#update'
	patch 'documents/update_status', to: 'documents#update_status'
	put 'documents/update_status', to: 'documents#update_status'

  get '/documents/:id', to: 'documents#docview'

  root 'sessions#new'
  get 'browse/index', to: 'documents#index'
  get 'master_matrices/index'
  get 'master_matrices/delete'

	resources :abet_metrics, only: [:create, :destroy]
  resources :documents, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :course_track_lists
  resources :libraries
  resources :approvers
  resources :master_matrices
  resources :sys_admin, only: [:index]
  resources :abet_outcomes
  resources :documents
  resources :degrees
  resources :tracks
  resources :courses
  resources :users
  resources :teachings
  resources :offerings, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :pies
  resources :airs
  resources :eocms
	
	put 'offerings/evaluation/:id', to: 'offerings#evaluation'
	put 'abet_metrics/evaluation/:id', to: 'abet_metrics#evaluation'

  get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

end

Implementation/ABET_Document_Manager/app/models/document.rb
class Document < ActiveRecord::Base
	has_one :library
	has_one :offering, through: :library
	has_many :resources
	has_many :comments
	has_one :form
	#has_many :links

	
	filterrific(
		default_filter_params: { sorted_by: 'due_asc' },
		available_filters: [
			:sorted_by,
			:with_status,
			:with_formType,
			:with_offering_course_code_prefix,
			:with_offering_course_code_suffix,
			:with_offering_year,
			:with_offering_term,
			:with_offering_user_name,
			:with_offering_fname_and_lname
		]
	)

	scope :with_status, lambda { |statuses|
		if (statuses == [""])
			all
		else
			where(status: [*statuses])
		end
	}

	scope :with_formType, lambda { |formTypes|
		if (formTypes == [""])
			all
		else
			where(formType: [*formTypes])
		end
	}

	scope :with_offering_course_code_prefix, lambda { |prefix|
		if (prefix == [""])
			all
		else
			#where(code_prefix: [*prefix]).joins(offering: :course)
			where('code_prefix in (?)', prefix).joins(offering: :course)
		end
	}

	scope :with_offering_course_code_suffix, lambda { |suffix|
		if (suffix == [""])
			all
		else
			where('code_suffix in (?)', suffix).joins(offering: :course)
		end
	}

	scope :with_offering_year, lambda { |year|
		if (year == [""])
			all
		else
			where('year in (?)', year).joins(:offering)
		end
	}

	scope :with_offering_term, lambda { |term|
		if (term == [""])
			all
		else
			where('term in (?)', term).joins(:offering)
		end
	}

	scope :with_offering_user_name, lambda { |username|
		if (username == [""])
			all
		else
			where('users.name in (?)', username).joins(offering: :user)
		end
	}

  scope :with_offering_fname_and_lname, lambda { |names|
    if (names == [""])
      all
    else
      usernames = []
      @name_parts = names.first.split
      names.each do |n|
        usernames.push (User.find_by(fname: n.split.first,
                                    lname: n.split.last).name)
      end

      where('users.name in (?)', usernames).joins(offering: :user)
    end
  }


	scope :sorted_by, lambda { |sort_option|
		direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
		case sort_option.to_s
		when /^user_/
			order("users.name #{ direction }").includes(offering: :user)
		when /^assigned_/
			order("documents.assigned #{ direction }")
		when /^due_/
			order("documents.assigned #{ direction }")
		end
	}

	def self.options_for_sorted_by
    [
			['User (A-Z)', 'user_asc'],
			['User (Z-A)', 'user_desc'],
      ['Date Assigned (newest first)', 'assigned_desc'],
      ['Date Assigned (oldest first)', 'assigned_asc'],
			['Date Due (newest first)', 'due_desc'],
			['Date Due (oldest first)', 'due_asc']
    ]
  end

end

Implementation/ABET_Document_Manager/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	include ApplicationHelper

  def index

	usr = ''
	if (current_user.permission == 'I')
		usr = current_user.name
		default_statuses = ['Not Submitted', 'Revisions Required']
	elsif (current_user.permission == 'C' || current_user.permission == 'A')
		default_statuses = ['Not Reviewed']
	end

	@filterrific = initialize_filterrific(
      Document,
      params[:filterrific],
      select_options: {
        sorted_by: Document.options_for_sorted_by,
				with_offering_user_name: User.all.pluck('DISTINCT name'),
				with_offering_fname_and_lname: get_full_names,
        with_status: Document.all.pluck('DISTINCT status'),
        		with_id: Document.all.pluck('DISTINCT id'), # Added to get and pass row id of clicked to docview, not printed.
				with_formType: Document.all.pluck('DISTINCT formType'),
				with_offering_course_code_prefix: Course.all.pluck('DISTINCT code_prefix'),
				with_offering_course_code_suffix: Course.all.pluck('DISTINCT code_suffix'),
				with_offering_term: Offering.all.pluck('DISTINCT term'),
				with_offering_year: Offering.all.pluck('DISTINCT year')
      },
      default_filter_params: { :with_offering_user_name => usr,
																:with_status => default_statuses,
														:sorted_by => 'due_asc'},
    ) or return

		@documents = @filterrific.find.page(params[:page]).paginate(page: params[:page], per_page: 20)
		@documents = @documents.includes(:offering).where.not(offerings: {id: nil})
		@documents = @documents.includes(offering: :user).where.not(users: {id: nil})
		
		respond_to do |format|
      format.html
      format.js
    end

		def reset_filterrific
			#Clear session persistence
			session[:filterrific] = nil
		  # Redirect back to the index action for default filter settings.
			redirect_to action: :index
		end

  rescue ActiveRecord::RecordNotFound => e
    # There is an issue with the persisted param_set. Reset it.
    puts "Had to reset filterrific params: #{ e.message }"
    redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def update
  	document = Document.find_by(id: params[:doc_id])
  	if document.update(status: "Not Reviewed")
  		redirect_to :back #Add notice
  	else
  		redirect_to :back #Add error
  	end
  end

	def update_status
		document = Document.find_by(id: params[:doc_id])
		document.update(status: params[:new_status])
		redirect_to :back
	end

  def docview
  	@data = Document.joins(:offering => [:course, :user]).where("documents.id = ?", params[:row_id])
  end

  	def all
		@documents = Document.joins(:offering => [:course, :user])
	end

	def show
		@document = Document.joins(:offering => [:course, :user]).find params[:id]
	end

	def edit
		@document = Document.find params[:id]
	end

	def update
		document = Document.find params[:id]
		if document.update_attributes(document_params)
			redirect_to sys_admin_index_path, :notice => 'The document has successfully been updated.'
		else
			redirect_to :back, :notice => 'There was an error updating the document.'
		end
	end

	def create
		Document.create(document_params)
		redirect_to :back, :notice => 'The document has successfully been created.'
	end

	def destroy
		Document.destroy params[:id]
		redirect_to :back, :notice => "The document has been removed."
	end

	private
	def document_params
		params.require(:document).permit(:name, :status, :assigned, :due, :formType)
	end
end

Implementation/ABET_Document_Manager/app/helpers/documents_helper.rb
module DocumentsHelper
end

Implementation/ABET_Document_Manager/app/views/documents/_list.html.erb
<%# app/views/documents/_list.html.erb %>

<div id="filterrific_results">
  <div>
  </div>

  <table class="table">
    <tr>
			<th>Instructor</th>
			<th>Type</th>
			<th>CRN</th>
			<th>Dept</th>
			<th>Course</th>
			<th>Section</th>
			<th>Year</th>
			<th>Term</th>
      <th>Status</th>
      <th><%= filterrific_sorting_link(@filterrific, :assigned) %></th>
			<th><%= filterrific_sorting_link(@filterrific, :due) %></th>
    </tr>
    <% documents.each do |document| %>
      <tr>
				<td><%= document.offering.user.fname%> <%= document.offering.user.lname%></td>
				<%# Makes text inside column a link to the docview action, and send doc.id as a paramater named row_id%>
				<td><%= link_to(document.formType, {:action => 'docview', :row_id => document.id}) %></td>
				<td><%= document.offering.CRN %></td>
				<td><%= document.offering.course.code_prefix %></td>
				<td><%= document.offering.course.code_suffix %></td>
				<td><%= document.offering.section %></td>
				<td><%= document.offering.year %></td>
				<td><%= document.offering.term %></td>
        <td><%= document.status %></td>
        <td><%= document.assigned.to_time.strftime('%B %e %Y') %></td>
				<td><%= document.due.to_time.strftime('%B %e %Y') %></td>
      </tr>
    <% end %>
  </table>

	<%= will_paginate documents %>

</div>

Implementation/ABET_Document_Manager/app/views/documents/all.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <h2><span class="label label-primary">Document Index</span></h2>
  
 <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#documentAdd">Add Document</button>

 <div id="documentAdd" class="collapse">

  <%= form_for Document.new, class: 'form-inline'   do |f| %>
  <%= f.label :name  %>
  <%= f.text_field :name,  {class: "form-control", 
                            style:  "width:350px"} %>
  <%= f.label :status %>
  <%= f.select :status, 
                options_for_select(["Not Submitted",
                "Not Reviewed", "Revisions Required", 
                "Approved - Complete"]) %>
  <div class="form-group" id="post_date_time">
    <%= f.label :assigned  %>
    <div class='input-group date' >
    <%= f.text_field :assigned,  {class: "form-control datetimepicker",
                                style:  "width:350px"} %>
    </div>
  </div>
  <div class="form-group" id="post_date_time">
    <%= f.label :due  %>
    <div class='input-group date' >
    <%= f.text_field :due,  {class: "form-control datetimepicker", 
                            style:  "width:350px"} %>
    </div>
  </div>
  <%= f.label "Form type:"  %>
  <%= f.select :formType, 
                options_for_select(["EOCM", "PIE", "AIR"]) %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %>
 </div> 
  <!-- Table for degrees -->
  <table class="table"  >
   
    <thead>
      <tr>
        <th><%= "Type: "%></th>
        <th><%= "Status: "%></th>
        <th><%= "Major: "%></th>
        <th><%= "Course Number: "%></th>
        <th><%= "Section: "%></th>
        <th><%= "Course: "%></th>
        <th><%= "Term: "%></th>
        <th><%= "Assigned: "%></th>
        <th><%= "Due: "%></th>
        <th><%= "Assigned To: "%></th>
      </tr>
    </thead>
    
    <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.formType%></td>
        <td><%= document.status%></td>
        <td><%= document.offering.course.code_prefix%></td>
        <td><%= document.offering.course.code_suffix%></td>
        <td><%= document.offering.section%></td>
        <td><%= document.offering.course.name%></td>
        <td><%= document.offering.term%></td>
        <td><%= document.assigned%></td>
        <td><%= document.due%></td>
        <td><%= document.offering.user.name%></td>
        <td> <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>  <%= link_to 'Details', document_path(document) %></td>
      </tr>
   <% end %>
  
    </tbody>
    
  </table>
      
      <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>

</div>

<script type="text/javascript">
  $(function () {
    $('.datetimepicker').datetimepicker({defaultDate: "<%= @document.assigned %>", format: "YYYY-MM-DD hh:mm a "
    });
  });
</script>

Implementation/ABET_Document_Manager/app/views/documents/docview.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <h2><span class="label label-primary">Document Description</span></h2>
  
  <!-- Table for degrees -->
  <table class="table"  >
   
    <thead>
      <tr>
        <th><%= "Type: "%></th>
        <th><%= "Status: "%></th>
        <th><%= "Major: "%></th>
        <th><%= "Course Number: "%></th>
        <th><%= "Section: "%></th>
        <th><%= "Course: "%></th>
        <th><%= "Term: "%></th>
        <th><%= "Assigned: "%></th>
        <th><%= "Due: "%></th>
 <!--       <th><%= "Assigned By: "%></th>  -->
        <th><%= "Assigned To: "%></th>
      </tr>
    </thead>
    
    <tbody>
    <% @data.each do |document| %>
      <tr>
        <td><%= document.formType%></td>
        <td><%= document.status%></td>
        <td><%= document.offering.course.code_prefix%></td>
        <td><%= document.offering.course.code_suffix%></td>
        <td><%= document.offering.section%></td>
        <td><%= document.offering.course.name%></td>
        <td><%= document.offering.term%></td>
        <td><%= document.assigned%></td>
        <td><%= document.due%></td>
<!--        <td><%= "James Kirk"%></td>	-->
        <td><%= document.offering.user.name%></td>
				<%form = nil %>
        <% if document.formType == "AIR"%>
					<% if AIR.exists?(document_id: document.id) %>
		    		<% form = 'airs' %>
					<% else %>
						<h4>Coordinator must initialize form</h4>
					<% end %>
	    <% elsif document.formType == "EOCM"%>
				<% if EOCM.exists?(document_id: document.id) %>
		    	<% form = 'eocms' %>
				<% else %>
					<h4>Coordinator must initialize form</h4>
				<% end %>
	    <% else document.formType == "PIE"%>
				<% if PIE.exists?(document_id: document.id) %>
		    	<% form = 'pies' %>
				<% else %>
					<h4>Coordinator must initialize form</h4>
				<% end %>
	    <% end %>

			<% if form != nil %>
	    	<td><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span><%= link_to("Details", {:controller => form, :action => 'index', :doc_id => document.id}) %></td>
      	</tr>
			<% end %> 
   <% end %>
  
    </tbody>
    
  </table>
      <%= link_to "<button type='button' class='btn btn-default'> Home </button>".html_safe , '/browse/index' %>

</div>

Implementation/ABET_Document_Manager/app/views/documents/edit.html.erb
<center>
<h1><span class="label label-primary">Editing Document</span></h1>
</center>  
  <%= form_for @document, class: 'form-inline'   do |f| %>
  <%= f.label :name  %>
  <%= f.text_field :name,  {class: "form-control", 
                            style:  "width:350px"} %>
  <%= f.label :status %>
  <%= f.select :status, 
                options_for_select(["Not Submitted",
                "Not Reviewed", "Revisions Required", 
                "Approved - Complete"]) %>
  <div class="form-group" id="post_date_time">
    <%= f.label :assigned  %>
    <div class='input-group date' >
    <%= f.text_field :assigned,  {class: "form-control datetimepicker",
                                style:  "width:350px"} %>
    </div>
  </div>
  <div class="form-group" id="post_date_time">
    <%= f.label :due  %>
    <div class='input-group date' >
    <%= f.text_field :due,  {class: "form-control datetimepicker", 
                            style:  "width:350px"} %>
    </div>
  </div>
  <%= f.label "Form type:"  %>
  <%= f.select :formType, 
                options_for_select(["EOCM", "PIE", "AIR"]) %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %> 
  </div>


  <center>
  <%= link_to "<button type='button' class='btn btn-danger'> Cancel </button>".html_safe , '/browse/index'%>
  </center>

<script type="text/javascript">
  $(function () {
    $('.datetimepicker').datetimepicker({defaultDate: "<%= @document.assigned %>", format: "YYYY-MM-DD hh:mm a "
    });
  });
</script>

Implementation/ABET_Document_Manager/app/views/documents/index.html.erb
<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
  <div>

   <div class="form-inline">
   <center>
   
  <label >User</label>
    <%= f.select(
      :with_offering_fname_and_lname,
      @filterrific.select_options[:with_offering_fname_and_lname],
      { include_hidden: false, include_blank: '- Any -' },  { multiple: true, style:  "width:200px",  class: "form-control"}
    ) %>
       <label >Type</label>
		<%= f.select(
      :with_formType,
      @filterrific.select_options[:with_formType],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}
    ) %>
       <label >Status</label>
		<%= f.select(
      :with_status,
      @filterrific.select_options[:with_status],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:200px",  class: "form-control"}
    ) %>
    
       <label >Major</label>
    <%= f.select(
      :with_offering_course_code_prefix,
      @filterrific.select_options[:with_offering_course_code_prefix],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}

    ) %>
       <label >Course</label>
    <%= f.select(
      :with_offering_course_code_suffix,
      @filterrific.select_options[:with_offering_course_code_suffix],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}

    ) %>
       <label >Year</label>
    <%= f.select(
      :with_offering_year,
      @filterrific.select_options[:with_offering_year],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}

    ) %>
       <label >Term</label>
    <%= f.select(
      :with_offering_term,
      @filterrific.select_options[:with_offering_term],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}

    ) %>
    
     </center>




  <div style="margin-top:15px"></div>
  

  
  <div class="form-inline" style="margin-left:15px">
    <label >Sorted by</label>
    
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by],{}, {style:  "width:300px",  class: "form-control"}) %>
  </div>
   

   
    
  <div style="margin-top:10px"></div>  
       <div class="form-inline">
        <center>
        <%# add an automated spinner to your form when the list is refreshed %>
        <%= render_filterrific_spinner %>
        <%= f.submit 'Filter', class: 'btn btn-success btn-xl' %>
        <% end %>
  
        <%= link_to(
        'Reset filters',
        reset_filterrific_url, :class =>"btn btn-danger btn-xl"
        ) %>
       </center>
      </div>
	<div style="margin-top:5px"></div>

<%= render(
  partial: 'documents/list',
  locals: { documents: @documents }
) %>

Implementation/ABET_Document_Manager/app/views/documents/index.js.erb
<% js = escape_javascript(
  render(partial: 'documents/list', locals: { documents: @documents })
) %>
$("#filterrific_results").html("<%= js %>");

Implementation/ABET_Document_Manager/app/views/documents/show.html.erb
<% d = @document %>
 <center>
 <h2><span class="label label-primary">Showing Document  </span></h2>

		<%= "Type: "%><%= d.formType%><br>
        <%= "Status: "%><%= d.status%><br>
        <%= "Major: "%><%= d.offering.course.code_prefix%><br>
        <%= "Course Number: "%><%= d.offering.course.code_suffix%><br>
        <%= "Section: "%><%= d.offering.section%><br>
        <%= "Course: "%><%= d.offering.course.name%><br>
        <%= "Term: "%><%= d.offering.term%><br>
        <%= "Assigned: "%><%= d.assigned%><br>
        <%= "Due: "%><%= d.due%><br>
        <%= "Assigned To: "%><%= d.offering.user.name%><br>
 

  <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>
  <%= link_to "<button type='button' class='btn btn-default'> Edit </button>".html_safe , edit_document_path(d)  %>
 </center>