Implementation/ABET_Document_Manager/config/routes.rb
Rails.application.routes.draw do

  
  get 'offerings/index'
  get 'offerings/view', to: 'offerings#view'
	

  get 'documents/docview', to: 'documents#docview'
  get 'documents/all', to: 'documents#all'
  
  patch 'documents/update', to: 'documents#update'
  put 'documents/update', to: 'documents#update'
	patch 'documents/update_status', to: 'documents#update_status'
	put 'documents/update_status', to: 'documents#update_status'

  get '/documents/:id', to: 'documents#docview'

  root 'sessions#new'
  get 'browse/index', to: 'documents#index'
  get 'master_matrices/index'
  get 'master_matrices/delete'

	resources :abet_metrics, only: [:create, :destroy]
  resources :documents, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :course_track_lists
  resources :libraries
  resources :approvers
  resources :master_matrices
  resources :sys_admin, only: [:index]
  resources :abet_outcomes
  resources :documents
  resources :degrees
  resources :tracks
  resources :courses
  resources :users
  resources :teachings
  resources :offerings, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :pies
  resources :airs
  resources :eocms
	
	put 'offerings/evaluation/:id', to: 'offerings#evaluation'
	put 'abet_metrics/evaluation/:id', to: 'abet_metrics#evaluation'

  get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

end

Implementation/ABET_Document_Manager/app/models/offering.rb
class Offering < ActiveRecord::Base
  belongs_to :course
	has_many :libraries
	has_many :documents, :through => :libraries
	has_one :teaching
	has_one :user, :through => :teaching
	has_many :AbetMetrics

	##############
	# Validation #
	##############

	# CRN
	# Force numeric, existence, unique
	validates :CRN, presence: true,
		numericality: {only_integer: true},
		uniqueness: { case_sensitive: false }
	
	# section
	# Force numeric, existence
	validates :section, presence: true,
		numericality: {only_integer: true}

	# year
		## Not yet: should also force an actual year
	# Force numeric
	# Force existence
	validates :year, presence: true,
		numericality: {only_integer: true}

	# term
	# Force numeric, existence
	validates :term, presence: true,
		numericality: {only_integer: true}

	# evaluation
	# Force either 'Pass', 'Fail', 'Other', 'Null'
	#validates :evaluation, presence: true,
	#	:inclusion => ["Pass", "Fail", "Other", "--"]

	# course
	# Force existence
	validates :course, presence: true

	#####################
	# START FILTERRIFIC #
	#####################

	# All in this section is used for filters
	# in the Tracker page

	filterrific(
		default_filter_params: { },
		available_filters: [
			:with_course_code_prefix,
			:with_course_code_suffix, 
			#:with_section,
			:with_fname_and_lname,
			#:with_evaluation,
			:with_year
		]
	)

		scope :with_year, lambda { |years| 
			if (years == [""])
				all
			else
				where(year: [*years])
			end
		}

		scope :with_course_code_prefix, lambda { |prefix|
			if (prefix == [""])
				all
			else
				where('code_prefix in (?)', prefix).joins(:course)
			end
		}

		scope :with_course_code_suffix, lambda { |suffix|
			if (suffix == [""])
				all
			else
				where('code_suffix in (?)', suffix).joins(:course)
			end
		}

		scope :with_fname_and_lname, lambda { |names|
			if (names == [""])
				all
			else
				usernames = []
				@name_parts = names.first.split
				names.each do |n|
					usernames.push (User.find_by(fname: n.split.first, 
																			lname: n.split.last).name)
				end

				where('users.name in (?)', usernames).joins(:user)
			end
		}

	###################
	# END FILTERRIFIC #
	###################
end

Implementation/ABET_Document_Manager/app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
	include ApplicationHelper

	def index

		#########################
		# BEGIN filter handling #
		#########################

		@filterrific = initialize_filterrific(
			Offering,
			params[:filterrific],
			select_options: {
				with_course_code_prefix: Course.all.pluck('DISTINCT code_prefix'),
				with_course_code_suffix: Course.all.pluck('DISTINCT code_suffix'),
				#with_section,
				with_fname_and_lname: get_full_names,
				#with_evaluation,
				with_year: Offering.all.pluck('DISTINCT year')
			}
		) or return

		@offerings = @filterrific.find.page(params[:page]).paginate(page: params[:page], per_page: 20)
		@offerings = @offerings.includes(:user).where.not(users: {id: nil})

		respond_to do |format|
		  format.html
		  format.js
	end

	def reset_filterrific
	  #Clear session persistence
	  session[:filterrific] = nil
	  # Redirect back to the index action for default filter settings.
	  redirect_to action: :index
	end

	rescue ActiveRecord::RecordNotFound => e
		# There is an issue with the persisted param_set. Reset it.
		puts "Had to reset filterrific params: #{ e.message }"
		redirect_to(reset_filterrific_url(format: :html)) and return
	end

		#######################
		# END filter handling #
		#######################

	def view
		@offerings = Offering.joins(:course)
	end

	def show
		@offering = Offering.joins(:course).find params[:id]
	end

	def edit
		@offering = Offering.find params[:id]
	end

	def update
		offering = Offering.find params[:id]
		if offering.update_attributes(offering_params)
			redirect_to sys_admin_index_path, :notice => 'The offering has successfully been updated.'
		else
			redirect_to :back, :notice => 'There was an error updating the offering.'
		end
	end

	def create
		Offering.create(offering_params)
		redirect_to :back, :notice => 'The offering has successfully been created.'
	end

	def destroy
		Offering.destroy params[:id]
		redirect_to :back, :notice => "The offering has been removed."
	end



	# Function: evaluation
	# Purpose:
	# 	Changes the current evaluation status
	# 	Modifes 'offering.evaluation'
	# 	Cycles through the possible statuses
	
	def evaluation
	@offering = Offering.find params[:id]
		if (@offering.evaluation == "--")
			@offering.update_attribute(:evaluation, "Fail")
		elsif (@offering.evaluation == "Fail")
			@offering.update_attribute(:evaluation, "Pass")
		elsif (@offering.evaluation == "Pass")
			@offering.update_attribute(:evaluation, "Other")
		elsif (@offering.evaluation == "Other")
			@offering.update_attribute(:evaluation, "--")
		else
			@offering.update_attribute(:evaluation, "Fail")
		end

		redirect_to :back
	end


	private
	def offering_params
		params.require(:offering).permit(:CRN, :section, :year, :term, 
															:course_id, :evaluation)
	end



end

	# Function: GetColorFromEvaluation
	# Purpose:
	# 	Maps an evaluation status 
	# 	to its corrosponding color code

	def GetColorFromEvaluation(evaluation)
		evaluation = evaluation.downcase
		case evaluation
		when "pass"
			return "5cb85c"
		when "fail"
			return "d9534f"
		when "other"
			return "800080"
		else
			return "5bc0de"
		end
	end

Implementation/ABET_Document_Manager/app/helpers/offerings_helper.rb
module OfferingsHelper
end

Implementation/ABET_Document_Manager/app/views/offerings/_list.html.erb
<div id="filterrific_results">
  <div>
  </div>
  <table class="table table-bordered">
    <tr>
      <th>Year</th>
			<th>CRN</th>
      <th>Dept</th>
      <th>Course</th>
      <th>Section</th>
      <th>Name</th>
      <th>Instructor</th>
      <th>Evaluation</th>
    <% ("A".."Q").each do |i|%>
				<th><%=i%></th>
		<%end%>
			</tr>
    <% offerings.each do |offering| %>
      <tr>
        <td><%= offering.year %></td>
        <td><%= offering.CRN %></td>
        <td><%= offering.course.code_prefix %></td>
        <td><%= offering.course.code_suffix %></td>
        <td><%= offering.section %></td>
				<td><%= offering.course.name %></td>
        <td><%= offering.user.fname %> <%= offering.user.lname %></td>

        <td bgColor="<%=GetColorFromEvaluation offering.evaluation %>">
	
				<!-- This section allows a coordinator to evaluate an offering -->
				<% if current_user.permission == "C" %>
				<b><center>
					<%= link_to("change",
						{:controller => 'offerings',
						:action => 'evaluation',
						:id => offering.id,
						}, {:style => "color:#ffffff;", method: :put}) %>
				</center></b>
				<% end %>
				</td>


		<% ("A".."Q").each do |i|%>
				<td 
				<% if offering.AbetMetrics.find_by(abet: i).present? == TRUE%>	
					bgColor="<%=GetColorFromEvaluation offering.AbetMetrics.find_by(abet: i).rating%>"
				<%else%>
					bgColor="5bc0de"
				<%end%>
			>

				<% if current_user.permission == "C" %>
					<% if offering.AbetMetrics.find_by(abet: i).present? == TRUE %>
						<b><center>
									<%=	link_to("change", 
									{:controller => 'abet_metrics',
									:action => 'evaluation',
									:id => offering.AbetMetrics.find_by(abet: i).id
									}, {:style => "color:#ffffff;", method: :put}) %>
						</center></b>
						<b><center>
									<%= link_to("delete",
									{:controller => 'abet_metrics',
									:action => 'destroy',
									:id => offering.AbetMetrics.find_by(abet: i).id
									}, {:style => "color:#ffffff;", method: :delete}) %>
						</center></b>
					<% else %>
						<b><center>
									<%= link_to("add",
									{:controller => 'abet_metrics',
									:action => 'create',
									#:id => [offering.id, i]
									:id => offering.id,
									:abet => i
									},{:style => "color:#ffffff;", method: :create}) %>
						</center></b>
					<% end %>
				<% end %>

			</td>
		<%end%>
			
      </tr>
    <% end %>
  </table>

  <%= will_paginate offerings %>

</div>

~                 

Implementation/ABET_Document_Manager/app/views/offerings/edit.html.erb
<center>
<h1><span class="label label-primary">Editing Offering</span></h1>
</center>  
  <%= form_for @offering, class: 'form-inline' do |f| %>
  <%= f.label :CRN %>
  <%= f.text_field :CRN , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :section %>
  <%= f.text_field :section , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :year %>
  <%= f.text_field :year, {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :term %>
  <!-- <%= f.text_field :term ,{class: "form-control" , style:  "width:350px"} %> -->
  <%= f.select :term, (1..12) %>
  <%= f.label :evaluation %>
  <!-- <%= f.text_field :evaluation , {class: "form-control" , style:  "width:350px"} %> -->
  <%= f.select :evaluation, options_for_select(["Pass", "Fail", "Other", "--"]) %>
  <%= f.label :course_id %>
  <!-- <%= f.text_field :course_id, {class: "form-control" , style:  "width:350px"} %> -->
  <%= f.collection_select :course_id, Course.all.order('name ASC'), :id, :name, :prompt => "Select" %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %> 
  </div>


  <center>
  <%= link_to "<button type='button' class='btn btn-danger'> Cancel </button>".html_safe , sys_admin_index_path%>
  </center>

Implementation/ABET_Document_Manager/app/views/offerings/index.html.erb
<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit' } do |f| %>
  <div>
   
   <div class="form-inline">
   <center>
   <label >Year</label>
    
    <%= f.select(
      :with_year,
      @filterrific.select_options[:with_year],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}
    ) %>
    <label >Dept</label>
    
    <%= f.select(
      :with_course_code_prefix,
      @filterrific.select_options[:with_course_code_prefix],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}
    ) %>
    <label >Course</label>
    
    <%= f.select(
      :with_course_code_suffix,
      @filterrific.select_options[:with_course_code_suffix],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:100px",  class: "form-control"}
    ) %>
    <label >Instructor</label>
    
    <%= f.select(
      :with_fname_and_lname,
      @filterrific.select_options[:with_fname_and_lname],
      { include_hidden: false, include_blank: '- Any -' }, { multiple: true, style:  "width:200px",  class: "form-control"}

    ) %>
  
       </center>
  
       <div style="margin-top:10px"></div>

       <div class="form-inline">
        <center>
    
    
    
            <%# add an automated spinner to your form when the list is refreshed %>
            <%= render_filterrific_spinner %>
                <%= f.submit 'Filter', class: 'btn btn-success'  %>
            <% end %>
            
            
        
            <%= link_to(
            'Reset filters',  
            reset_filterrific_url, :class =>"btn btn-danger btn-xl"
            ) %>
        


        </center>
      </div>
    </div>
 </div>
<div style="margin-top:5px"></div>

<%= render(
  partial: 'offerings/list',
  locals: { offerings: @offerings }
) %>

Implementation/ABET_Document_Manager/app/views/offerings/index.js.erb
<% js = escape_javascript(
  render(partial: 'offerings/list', locals: { offerings: @offerings })
) %>
$("#filterrific_results").html("<%= js %>");

Implementation/ABET_Document_Manager/app/views/offerings/show.html.erb
<% o = @offering %>
 <center>
 <h2><span class="label label-primary">Showing Offering  </span></h2>

 <%= "CRN: "%><%= o.CRN %><br>
 <%= "Section: "%><%= o.section %><br>
<%= "Year: "%><%= o.year %><br>
<%= "Term: "%><%= o.term %><br>
<%= "Evaluation: "%><%= o.evaluation %><br>
<%= "Course: "%><%= o.course.name %><br>
 

  <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>
  <%= link_to "<button type='button' class='btn btn-default'> Edit </button>".html_safe , edit_offering_path(o)  %>
 </center>

Implementation/ABET_Document_Manager/app/views/offerings/view.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <h2><span class="label label-primary">Offerings Index</span></h2>
  
   <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#offeringAdd">Add Offering</button>

  
   <div id="offeringAdd" class="collapse">

  <%= form_for Offering.new , class: 'form-inline' do |f| %>
  <%= f.label :CRN %>
  <%= f.text_field :CRN , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :section %>
  <%= f.text_field :section , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :year %>
  <%= f.text_field :year, {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :term %>
  <%= f.text_field :term ,{class: "form-control" , style:  "width:350px"} %>
  <%= f.label :evaluation %>
  <%= f.text_field :evaluation , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :course_id %>
  <%= f.text_field :course_id, {class: "form-control" , style:  "width:350px"} %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %>   
  </div>
  <!-- Table for degrees -->
  <table class="table"  >
   
    <thead>
      <tr>
        <th><%= "CRN: "%></th>
        <th><%= "Section: "%></th>
        <th><%= "Year: "%></th>
        <th><%= "Term: "%></th>
        <th><%= "Evaluation: "%></th>
        <th><%= "Course: "%></th>
      </tr>
    </thead>
    
    <tbody>
    <% @offerings.each do |offering| %>
      <tr>
        <td><%= offering.CRN %></td>
        <td><%= offering.section %></td>
        <td><%= offering.year %></td>
        <td><%= offering.term %></td>
        <td><%= offering.evaluation %></td>
        <td><%= offering.course.name %></td>
        <td> <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>  <%= link_to 'Details', offering_path(offering) %></td>
      </tr>
   <% end %>
  
    </tbody>
    
  </table>
      
      <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>

</div>