Implementation/ABET_Document_Manager/config/routes.rb
Rails.application.routes.draw do

  
  get 'offerings/index'
  get 'offerings/view', to: 'offerings#view'
	

  get 'documents/docview', to: 'documents#docview'
  get 'documents/all', to: 'documents#all'
  
  patch 'documents/update', to: 'documents#update'
  put 'documents/update', to: 'documents#update'
	patch 'documents/update_status', to: 'documents#update_status'
	put 'documents/update_status', to: 'documents#update_status'

  get '/documents/:id', to: 'documents#docview'

  root 'sessions#new'
  get 'browse/index', to: 'documents#index'
  get 'master_matrices/index'
  get 'master_matrices/delete'

	resources :abet_metrics, only: [:create, :destroy]
  resources :documents, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :course_track_lists
  resources :libraries
  resources :approvers
  resources :master_matrices
  resources :sys_admin, only: [:index]
  resources :abet_outcomes
  resources :documents
  resources :degrees
  resources :tracks
  resources :courses
  resources :users
  resources :teachings
  resources :offerings, only: [:create, :destroy, :edit, :new, :show, :update]
  resources :pies
  resources :airs
  resources :eocms
	
	put 'offerings/evaluation/:id', to: 'offerings#evaluation'
	put 'abet_metrics/evaluation/:id', to: 'abet_metrics#evaluation'

  get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

end

Implementation/ABET_Document_Manager/app/models/user.rb
class User < ActiveRecord::Base
	has_many :teachings, :dependent => :restrict_with_exception
	has_many :offerings, :through => :teachings, :dependent => :restrict_with_exception
	has_many :approvers, :dependent => :restrict_with_exception
	has_many :tracks, :through => :approvers, :dependent => :restrict_with_exception
	has_many :authors
	has_many :comments, :through => :authors
	has_many :uploaders
	has_many :resources, :through => :uploaders

	# Force a lower-case email
  before_save { self.email = email.downcase }
	# Username must exist and be < 50 characters
	validates :name, presence: true, length: { maximum: 50 }
	# Email must make sense
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	  format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }
	has_secure_password
	# Password must exist with minimum of 8 characters
	#validates :password, presence: true, length: { minimum: 8 }
	validates :password, presence: true, 
		if: Proc.new { |user| user.password.present? }, confirmation: true, on: :update
end

Implementation/ABET_Document_Manager/app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'securerandom'

  def index
  	@users = User.all
  end

  def show
  	@user = User.find params[:id]
  end

  def edit
  	@user = User.find params[:id]
  end

  def update
  	user = User.find params[:id]
  	if user.update_attributes(user_params)
  		redirect_to sys_admin_index_path, :notice => 'The user has successfully been updated.'
  	else
  		redirect_to :back, :notice => 'There was an error updating the user.'
  	end
  end

  def create
  	@usr = User.create(user_params)
		
		# Generate secure random password
		pass = SecureRandom.base64(12)
		@usr.update_attributes(password: pass, password_confirmation: pass)

		# Have the UserMailer send a welcome email
		UserMailer.pass_email(@usr, pass).deliver_now

		pass = 000000 #almost certainly useless, but an attempt to clear that variable

  	redirect_to :back, :notice => 'The user has successfully been created.'
  end

  def destroy
  	User.destroy params[:id]
  	redirect_to :back, :notice => "The user has been removed."
  end

  private
  def user_params
  	params.require(:user).permit(:name, :password, :fname, :lname, :email, :permission)
  end
end

Implementation/ABET_Document_Manager/app/helpers/users_helper.rb
module UsersHelper
end

Implementation/ABET_Document_Manager/app/views/users/edit.html.erb
<center>
<h1><span class="label label-primary">Editing User</span></h1>
</center>  
  <%= form_for  @user, class: 'form-inline'  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name , {class: "form-control" , style:  "width:350px"}  %>
  <%= f.label :fname %>
  <%= f.text_field :fname , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :lname %>
  <%= f.text_field :lname , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :email %>
  <%= f.text_field :email , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :permission %>
  <!-- <%= f.text_field :permission , {class: "form-control" , style:  "width:350px"} %> -->
  <%= f.select :permission, options_for_select([ ["I (instructor)", "I"], 
                              ["C (coordinator)", "C"], ["A (admin)", "A"], 
                              ["E (evaluator)", "C"] ]) %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %>   


  <center>
  <%= link_to "<button type='button' class='btn btn-danger'> Cancel </button>".html_safe , sys_admin_index_path%>
  </center>

Implementation/ABET_Document_Manager/app/views/users/index.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  
  <h2><span class="label label-primary">Users Index</span></h2>
  
  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#userAdd">Add User</button>
  <div id="userAdd" class="collapse">

 
  
  <%= form_for  User.new, class: 'form-inline'  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name , {class: "form-control" , style:  "width:350px"}  %>
  <%= f.label :password %>
  <%= f.text_field :password , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :fname %>
  <%= f.text_field :fname , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :lname %>
  <%= f.text_field :lname , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :email %>
  <%= f.text_field :email , {class: "form-control" , style:  "width:350px"} %>
  <%= f.label :permission %>
  <%= f.text_field :permission , {class: "form-control" , style:  "width:350px"} %>
  <div style="margin-top:10px" > </div>
  <%= f.submit :Submit, class: 'btn btn-success'  %>
  <% end %>   
  </div>
  <!-- Table for degrees -->
  <table class="table"  >
   
    <thead>
      <tr>
        <th><%= "Degree: "%></th>
      </tr>
    </thead>
    
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= user.permission %></td>
        <td> <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>  <%= link_to 'Details', user_path(user)%></td>
      </tr>
   <% end %>
  
    </tbody>
    
  </table>
  
      <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>

  
</div>

Implementation/ABET_Document_Manager/app/views/users/show.html.erb
<% u = @user %>
 <center>
 <h2><span class="label label-primary">Showing User: <%= u.name %></span></h2>
 <%= "User Name: "%><%= u.name %><br>
<%= "First Name: "%><%= u.fname %><br>
<%= "Last Name: "%><%= u.lname %><br>
<%= "Email: "%><%= u.email %><br>
<%= "Permission: "%><%= u.permission %><br>
 

  <%= link_to "<button type='button' class='btn btn-default'> Admin Page </button>".html_safe , sys_admin_index_path %>
  <%= link_to "<button type='button' class='btn btn-default'> Edit </button>".html_safe , edit_user_path(u)  %>
 </center>